### ISSUE TITLE
Switch from rabbitpy to a maintained client library such as pika

### ISSUE THREAD

**Issue by cakeisalie5** [ClearcodeHQ/pytest-rabbitmq#313]
### What action do you want to perform

Update `pytest-rabbitmq` to use a maintained client library such as [pika](https://pypi.org/project/pika/) instead of rabbitpy.

### What are the results

[rabbitpy](https://github.com/gmr/rabbitpy) hasn't been updated on PyPI [since 2019](https://pypi.org/project/rabbitpy/#history) (4 years ago!) and does not work with 3.x releases of [pamqp](https://pypi.org/project/pamqp/):

```
>>> from rabbitpy import Exchange, Queue, Connection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thomas/.cache/pypoetry/virtualenvs/teal-sCn2En4E-py3.11/lib/python3.11/site-packages/rabbitpy/__init__.py", line 24, in <module>
    from rabbitpy.connection import Connection
  File "/home/thomas/.cache/pypoetry/virtualenvs/teal-sCn2En4E-py3.11/lib/python3.11/site-packages/rabbitpy/connection.py", line 17, in <module>
    from rabbitpy import base
  File "/home/thomas/.cache/pypoetry/virtualenvs/teal-sCn2En4E-py3.11/lib/python3.11/site-packages/rabbitpy/base.py", line 13, in <module>
    from pamqp import specification
ImportError: cannot import name 'specification' from 'pamqp' (/home/thomas/.cache/pypoetry/virtualenvs/teal-sCn2En4E-py3.11/lib/python3.11/site-packages/pamqp/__init__.py)
```

This is blocking when using aio-pika or aioamqp, official clients with asyncio supports from [rabbitmq.com's list](https://www.rabbitmq.com/devtools.html), which require pamqp >=3.1.

### What are the expected results

Being able to use `pytest-rabbitmq` with referenced asyncio compatible libraries for RabbitMQ. For this, we need to have a library that supports recent releases of pamqp. [rabbitmq.com recommends pika](https://www.rabbitmq.com/devtools.html).

**Comment by cakeisalie5** [comment]
Thank you so much @kropatwakrzysztof @fizyk :)
